spring.application.name=SmartHabitat
server.port=3001
api.base.url=/api/smart-Habitat
api.graphDB = http://20.3.141.133:7200/repositories/SMH
api.graphDB.update = http://20.3.141.133:7200/repositories/SMH/statements

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

cors.allowed.origins=http://localhost:3000,https://purple-mushroom-050a3aa1e.4.azurestaticapps.net

